.map fn
mmkal/expect-type pull request #98
Opened 2024-08-12 13:00 UTC by mmkal

@aryaemami59 another potential helper that occurred to me might be useful. I'm not totally convinced it's worth it, but thought I'd open a draft PR in case you had thoughts. Given `.toBeCallableWith` doesn't work well for generic functions, it's a catch-all way to say "I am allowed to do this with my object" and make assertions on the result, without actually calling the function or performing side-effects, etc.:

```ts
const capitalize = <S extends string>(input: S) =>
  (input.slice(0, 1).toUpperCase() + input.slice(1)) as Capitalize<S>

expectTypeOf(capitalize)
  .map(fn => fn('hello world'))
  .toEqualTypeOf<'Hello world'>()
```

But the assertion could just as easily (maybe _more_ easily) be written as:

```ts
expectTypeOf(() => capitalize('hello world')).returns.toEqualTypeOf<'Hello world'>()
```

Which also doesn't actually call `capitalize` at runtime.

Advantages of `.map`:

- it makes it clearer its an asertion about `capitalize` rather than an inline callback.
- it works fine with `expectTypeOf<X>()` as well as `expectTypeOf(x)`

It could could also sub in for how we do `.toBeCallableWith` in #83 too:

```ts
type Factorize = {
  (input: number): number[]
  (input: bigint): bigint[]
}

expectTypeOf<Factorize>().map(f => f(12)).toEqualTypeOf<number[]>()
expectTypeOf<Factorize>().map(f => f(12n)).toEqualTypeOf<bigint[]>()
```

2024-08-13 05:06 UTC, aryaemami59 commented
Not sure about this one yet, I'd say let's get #83 in first then we can use this one to potentially fill in any left over gaps.

2025-02-13 10:55 UTC, mmkal commented
@aryaemami59 I keep forgetting this is still a draft. Not a particularly exciting feature but v small implementation cost and somewhat useful so I'd like to get it in. Let me know if you have any thoughts on the code.

2025-02-14 16:19 UTC, aryaemami59 requested changes

2025-02-14 16:19 UTC, aryaemami59 commented on src/index.ts
> +   * @param fn A callback that transforms the input value. Note that this function is not actually called - it's only used for type inference.
```suggestion
   * @param fn - A callback that transforms the input value. Note that this function is not actually called - it's only used for type inference.
```

2025-02-28 12:13 UTC, aryaemami59 approved these changes
Still not too sure about the name tbh, and we'll add more docs and examples later to cover some of the niche use cases. Other than all looks good to me.

2025-02-28 17:43 UTC, merged